//This is supposed to be the home, generated by Claude AIcd

import { Link } from "react-router-dom";
import "./Home.css";

export default function Home() {
  return (
    <div className="home-container">
      <div className="home-content">
        <h1>Welcome to Eatelligent</h1>
        <p className="tagline">Manage your recipes and ingredients with ease</p>
        
        <div className="home-buttons">
          <Link to="/recipes" className="btn btn-primary">
            View Recipes
          </Link>
          <Link to="/create" className="btn btn-secondary">
            Add New Recipe
          </Link>
        </div>

        <div className="features">
            <Link to="/pantry" className="feature-card">
                <h3>Pantry</h3>
                <p>Check out what's in your pantry now!</p>
            </Link>

          <div className="feature-card">
            <h3>Fridge</h3>
            <p>Check out what's in your fridge now!</p>
          </div>
          <div className="feature-card">
            <h3>Recipes</h3>
            <p>See what's recipes are in store for you!</p>
          </div>
        </div>
      </div>
    </div>
  );
}