//This is supposed to be the home, generated by Claude AIcd

import { Link } from "react-router-dom";
import "./Home.css";

export default function Home() {
  return (
    <div className="home-container">
      <div className="home-content">
        <h1>Welcome to Eatelligent</h1>
        <p className="tagline">Manage your recipes and ingredients with ease</p>
        
        <div className="home-buttons">
          <Link to="/recipes" className="btn btn-primary">
            View Recipes
          </Link>
          <Link to="/create" className="btn btn-secondary">
            Add New Recipe
          </Link>
        </div>

        <div className="features">
          <div className="feature-card">
            <h3>📝 Easy Management</h3>
            <p>Add, edit, and organize your recipes</p>
          </div>
          <div className="feature-card">
            <h3>🔍 Quick Search</h3>
            <p>Find recipes instantly</p>
          </div>
          <div className="feature-card">
            <h3>⭐ Save Favorites</h3>
            <p>Keep track of your best recipes</p>
          </div>
        </div>
      </div>
    </div>
  );
}